[package]
name = "umbra_oracle"
type = "contract"
authors = ["Umbra Protocol"]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v2.1.9", directory = "noir-projects/aztec-nr/aztec" }
